//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.573.
// 
namespace WinUI.net.mynamespace.www {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="LoginServicesSoap", Namespace="http://tempuri.org/")]
    public class LoginServices : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public LoginServices() {
            this.Url = "http://127.0.0.1/IssueTracker/IssueTracker_WebService/LoginServices.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValidateLogin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ValidateLogin(string strEmailAddress, string strPassword) {
            object[] results = this.Invoke("ValidateLogin", new object[] {
                        strEmailAddress,
                        strPassword});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginValidateLogin(string strEmailAddress, string strPassword, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ValidateLogin", new object[] {
                        strEmailAddress,
                        strPassword}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndValidateLogin(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckKey", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CheckKey(string strKey) {
            object[] results = this.Invoke("CheckKey", new object[] {
                        strKey});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCheckKey(string strKey, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CheckKey", new object[] {
                        strKey}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndCheckKey(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    }
}
